### PR TITLE
[WIP] Refactor using forecastio library

### PR DESCRIPTION
**Pull request by jeffbyrnes**
This is a major work-in-progress. @edhurtig & others, thoughts/assistance are very welcome here
- Use a library, instead of making raw HTTP calls to the Forecast.io API
- Abstract out code to be more OO, less callback hell
- Add tests

### CODE REVIEW

**Comment by EdHurtig** [comment]
@jeffbyrnes much cleaner! much like!

Was a big fan of the alerting code that pinged when there was bad weather in the next x minutes.  Assuming that's in the works seeing as you kept the `activeDays` stuff, right?

**Comment by jeffbyrnes** [comment]
@EdHurtig yep, that’s really the whole point of this package, in fact. If we just wanted on-demand weather alerts, we could just stick with [hubot-darksky](https://www.npmjs.com/package/hubot-darksky) & be done with it.

**Comment by jeffbyrnes** [comment]
At this point, this isn’t being actively maintained, so I don’t foresee this happening. Closing it out.

**Comment by EdHurtig** [comment]
💯

**Pull request closed without merging**
